version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:buster-scm
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
            docker build -t scotthal/docker-and-kubernetes -f Dockerfile.dev .
            docker run -e CI=true scotthal/docker-and-kubernetes npm run test
