version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: test
          command: |
            docker build -t scotthal/docker-and-kubernetes -f Dockerfile.dev .
            docker run -e CI=true scotthal/docker-and-kubernetes npm run test
      - run:
          name: deploy
          command: |
            docker build -t scotthal/docker-and-kubernetes .
