version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: test
          command: |
            docker build -t scotthal/docker-and-kubernetes -f Dockerfile.dev .
            docker run -e CI=true scotthal/docker-and-kubernetes npm run test
      - run:
          name: Elastic Beanstalk Dependencies
          command: |
            sudo pip install awsebcli --upgrade
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 0600 ~/.aws/config
            echo '[profile eb-cli]'' >> ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws.config
      - run:
          name: deploy
          command: |
            docker build -t scotthal/docker-and-kubernetes .
            eb use server-backend-env --profile eb-cli
            eb deploy -v --staged --profile eb-cli
