version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/python:3
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: test
          command: |
            docker build -t scotthal/docker-and-kubernetes -f Dockerfile.dev .
            docker run -e CI=true scotthal/docker-and-kubernetes npm run test
      - run:
          name: Elastic Beanstalk Dependencies
          command: |
            python -m venv ebenv
            . ebenv/bin/activate
            pip install awsebcli --upgrade
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 0600 ~/.aws/config
            echo '[profile eb-cli]' >> ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: deploy
          command: |
            . ebenv/bin/activate
            docker build -t scotthal/docker-and-kubernetes .
            eb use DockerAndKubernetes-env --profile eb-cli
            eb deploy -v --staged --profile eb-cli
