version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:buster-scm
    steps:
      - checkout
      - run:
          command: |
            docker build -t scotthal/docker-and-kubernetes -f Dockerfile.dev .
            docker run -e CI=true scotthal/docker-and-kubernetes npm run test
